# Generated by Django 5.1.1 on 2025-06-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petvital_app', '0005_alter_cita_nota_alter_cita_recordatorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
