# Generated by Django 3.2.23 on 2025-06-20 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petvital_app', '0006_alter_mascota_peso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petvital_app.mascota')),
            ],
        ),
    ]
