# Generated by Django 5.1.1 on 2025-06-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petvital_app', '0008_mascota_esterilizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='oneSignalId',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
