# Generated by Django 5.1.1 on 2025-06-23 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petvital_app', '0009_cita_onesignalid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='oneSignalId',
        ),
    ]
