# Generated by Django 5.2 on 2025-07-02 03:40

import petvital_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petvital_app', '0010_remove_cita_onesignalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fecha_registro',
            field=models.DateTimeField(default=petvital_app.models.get_lima_now),
        ),
    ]
