# Generated by Django 5.2 on 2025-07-02 04:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petvital_app', '0011_user_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
