# Generated by Django 3.2.23 on 2025-05-22 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petvital_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='usuario',
        ),
        migrations.AddField(
            model_name='cita',
            name='mascota',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='petvital_app.mascota'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='petvital_app.user'),
        ),
    ]
