# Generated by Django 3.2.23 on 2025-05-22 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petvital_app', '0002_auto_20250521_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petvital_app.mascota'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petvital_app.user'),
        ),
    ]
