# Generated by Django 5.1.1 on 2025-06-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petvital_app', '0003_auto_20250521_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='unidad_tiempo',
            field=models.CharField(default='años', max_length=100),
            preserve_default=False,
        ),
    ]
